### ISSUE TITLE
SSLError when hitting statsapi

### ISSUE THREAD

**Issue by kfinneman** [toddrob99/MLB-StatsAPI#110]
Starting getting this error today for some reason.`(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))`

I am hitting the statsapi module. when I do requests it works but don't really want to type to whole url since I am hitting a bunch of different endpoints haha

**Comment by kfinneman** [comment]
Any tips on how to fix it?

**Comment by toddrob99** [comment]
It should work the same whether you use this MLB-StatsAPI module or directly with requests, since that's what this wrapper module uses. I'm guessing you have proxy info set somewhere when you use requests but not where you're using the wrapper. Without knowing any details of your network I'm not sure what else I can do to help.

**Comment by kfinneman** [comment]
Thank you!
