### ISSUE TITLE
Tidying up codebase

### ISSUE THREAD

**Issue by Skellet0r** [toddrob99/MLB-StatsAPI#23]
After #22 has been implemented, it would be beneficial to cleanup the package init.py as well as the endpoints.py. For easier readability as well as interfacing in third party programs. Beyond formatting, it would be nicer to implement a better interface, currently a majority of the functions return formatted strings with the data from the API, instead of returning JSON.

Ideas:
* Remove redundant documentation within functions (since they are all well documented in the docs)
* Have functions return JSON instead of data within strings. (maybe give the option as a parameter to return a string or the JSON)
* Clean up init.py and factorize/modular-ize code, making related functions apart of a single sub module and then imported into init.py

**Comment by toddrob99** [comment]
﻿
I’m on vacation for the next week and will review and reply further when I get back home. 

Removing documentation from functions is something I’ve considered, but I believe I left it in because pdoc pulls from there to generate the documentation. I’ve been having difficulty with pdoc so I am open to other ideas. 

I’ve added functions to return data instead of formatted strings for the functions that included a lot of parsing of the data. The other built-in functions don’t do much with the data and a corresponding _data function would be redundant of just calling get() for the given endpoint. 

I put all the functions in init to keep it simple. Why do you think it’s better to have them in a sub-module? 

> On Oct 5, 2019, at 6:40 PM, Edward Amor <notifications@github.com> wrote:

﻿
After #22 has been implemented, it would be beneficial to cleanup the package init.py as well as the endpoints.py. For easier readability as well as interfacing in third party programs. Beyond formatting, it would be nicer to implement a better interface, currently a majority of the functions return formatted strings with the data from the API, instead of returning JSON.

Ideas:

Remove redundant documentation within functions (since they are all well documented in the docs)
Have functions return JSON instead of data within strings. (maybe give the option as a parameter to return a string or the JSON)
Clean up init.py and factorize/modular-ize code, making related functions apart of a single sub module and then imported into init.py

**Comment by toddrob99** [comment]
I've reviewed this again and I'm not sure there's much to do... Please provide feedback based on my last response, @Skellet0r.

**Comment by Skellet0r** [comment]
Well I rescind my earlier suggestion, it would only be beneficial to modularize the code base if a majority of the end users required something like objects returned from API calls. However, after looking at the forked repos, everyone is perfectly fine with just working with the returned dictionaries or string responses.
