### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by chisox721** [toddrob99/MLB-StatsAPI#6]
This could be an issue on my end but figured I would mention it just in case. When looping through dates my code will stop with an error like this: 

```
line 145, in schedule 'away_pitcher_note': game['teams']['away'].get('probablePitcher').get('note',''),
AttributeError: 'NoneType' object has no attribute 'get'
```
This only happens with certain dates and after testing it seems to be pretty random. Here is what my code looks like (changing end_date to 03/23/2019 will return an error for me).

```
for x in statsapi.schedule(start_date='03/20/2019',end_date='03/21/2019'):
    if (x['status'] in ['Final','Game Over'] and x['game_type'] in ['R']):
        print(x['game_id'])
    else:
        pass
```

**Comment by toddrob99** [comment]
This is due to my failure to account for a game with no probable pitcher listed when pulling pitcher reports. I did account for this when pulling the probable pitcher's name, but not the note. Specifically, gamePk=573193 on 3/23/19 did not have a probable pitcher listed for Canada Jr. Team (exhibition game, obviously). I have checked in the fix for v0.0.8. Thank you!

**Comment by toddrob99** [comment]
```
>>> import statsapi
>>> statsapi.__version__
'0.0.8'
>>> for x in statsapi.schedule(start_date='03/20/2019',end_date='03/23/2019'):
...     if (x['status'] in ['Final','Game Over'] and x['game_type'] in ['R']):
...         print(x['game_id'])
...     else:
...         pass
...
566083
566084
```

**Comment by toddrob99** [comment]
Please update to v0.0.8 with `pip install --upgrade MLB-StatsAPI`

**Comment by chisox721** [comment]
Just ran a few tests and looked good. Thanks for the quick update on this Todd!
