### ISSUE TITLE
Error: 'winning_pitcher': game['decisions'].get('winner',{}).get('fullName',''), KeyError: 'decisions'

### ISSUE THREAD

**Issue by philconow** [toddrob99/MLB-StatsAPI#9]
I ran the following with version 0.0.8 which was running fine a few weeks ago:

> import statsapi
> 
> start_date = '2019-03-28'
> end_date = '2019-06-25'
> 
> game_list_2019 = statsapi.schedule(start_date=start_date, end_date=end_date)
> 

And get back this error:

> Traceback (most recent call last):
>   File "C:/Test.py", line 16, in <module>
>     game_list_2019 = statsapi.schedule(start_date=start_date, end_date=end_date)
>   File "C:\Users\Philconow\AppData\Local\Programs\Python\Python37\lib\site-packages\statsapi\__init__.py", line 161, in schedule
>     'winning_pitcher': game['decisions'].get('winner',{}).get('fullName',''),
> KeyError: 'decisions'

**Comment by toddrob99** [comment]
Thank you for the report.

This happened because the decisions field is missing in the MLB data for a game. I thought MLB included the decisions field for all completed games, but perhaps there was a suspended game or something else out of the ordinary for which they leave that field out. I’ll take a closer look later today or tomorrow. 

The fix is easy regardless of why the data is not included. I just have to change game[‘decisions’] to game.get(‘decisions’,{}) to account for the field missing sometimes.

**Comment by philconow** [comment]
Thank you!

**Comment by toddrob99** [comment]
It's due to gamePk 565060 from 6/13 not having the decisions data included, but I don't see anything special about that game. It completed after 8.5 innings, the status is FInal, and the Red Sox beat the Rangers 7-6. [MLB Gameday](https://www.mlb.com/gameday/rangers-vs-red-sox/2019/06/13/565060?partnerId=LR_box#game_tab=box,game_state=final,game=565060) shows W/L/S in the pitching box score, but it is also missing a couple of names for the Red Sox (no name on the row after Brewer, and no name with the save credited). I'll add protection against missing decision data, but I don't know why it's missing.

**Comment by toddrob99** [comment]
Fixed in v0.0.9, update with `pip install --upgrade mlb-statsapi`.

Thank you for the bug report!
